name: marine_eov
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - aiohttp
  - bokeh
  - fsspec
  - h5netcdf
  - h5py
  - hdf4
  - hdf5
  - ipykernel
  - ipython
  - ipython_genutils
  - netcdf4
  - numpy
  - pandas
  - proj
  - python
  - requests
  - scipy
  - setuptools
  - shapely
  - xarray
  - yaml
  - notebook
  - pykg2tbl
  - pyrdfj2
