[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
  'pandas >= 1.3.4',
  'requests >= 2.26.0',
  'shapely >= 1.8.0',
  'sparqlwrapper >= 1.8.5',
  'xarray >= 0.20.1',
]